#:schema https://raw.githubusercontent.com/jdx/mise/refs/heads/main/schema/mise.json

[env]
# '_'.file = { path = ".env", required = false }
# _.nix = true

AllowOrigins = "*" # optional

DB_USERNAME = "honyabookstore"
DB_PASSWORD = "honyabookstore"
DB_DATABASE = "honyabookstore"
DB_PORT = 5432                                                                                      # optional
DB_HOST = "localhost"
DB_URL = "postgresql://honyabookstore:honyabookstore@localhost:5432/honyabookstore?sslmode=disable"
PORT = 8080                                                                                         # optional
TIMEZONE = "Asia/Ho_Chi_Minh"                                                                       # optional

# Keycloak
KC_CLIENT_ID = "backend"
KC_CLIENT_SECRET = "honyabookstore"
KC_REALM = "honyabookstore"
KC_BASE_PATH = "http://localhost:8081"
KC_HTTP_MANAGEMENT_PATH = "http://localhost:8082"

# S3 / S3 Compatible (MinIO)
S3_ACCESS_KEY = "honyabookstore"
S3_SECRET_KEY = "honyabookstore"
S3_REGION_NAME = "us-east-1"
S3_ENDPOINT = "http://localhost:9000"
S3_BUCKET = "honyabookstore"

# Public, mostly used in Swagger
PUBLIC_KEYCLOAK_URL = ""

# Redis / Redis Compatible
REDIS_ADDRESS = "localhost:6379"

# VNPay
VNP_URL = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VNP_HASH_ALGO = "SHA256"
VNP_SECURE_SECRET = ""                                         # vnp_HashSecret
VNP_TMN_CODE = ""                                              # vnp_TmnCode

[tools]
air = "latest"
atlas = "0.37.0"
go = "1.25.3"
"go:github.com/cweill/gotests/gotests" = "v1.6.0"
"go:github.com/google/wire/cmd/wire" = "0.7.0"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "1.30.0"
golangci-lint = "2.5.0"
just = "latest"
mc = "latest"
mockery = "3.5.5"
swag = "1.16.6"
terraform = "1.13.4"
