name: Main

on:
  workflow_dispatch:
    inputs:
      release:
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
        description: Release container
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.sql"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.sql"

env:
  MISE_OVERRIDE_CONFIG_FILENAMES: mise.ci.toml

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: jdx/mise-action@v3
        with:
          experimental: true

      - name: Install go deps
        run: go mod download

      - name: Check static type
        id: static-type
        run: just check-static-type

      - name: Sqlc diff
        id: check-sql
        run: sqlc diff
        continue-on-error: true

      - name: Make changes
        id: make-changes
        run: |
          go mod tidy
          just gen-wire
          just gen-swag -ot go
        continue-on-error: true

      - name: Check lint
        id: lint
        run: just lint
        continue-on-error: true

      - name: Fail check
        run: |
          declare -A check_status=(
            ["Static type check failed"]=${{ steps.static-type.outcome == 'failure' }}
            ["Make changes check failed"]=${{ steps.make-changes.outcome == 'failure' }}
            ["Sqlc diff failed"]=${{ steps.check-sql.outcome == 'failure' }}
            ["Lint check failed"]=${{ steps.lint.outcome == 'failure' }}
          )
          fail=false
          for msg in "${!check_status[@]}"; do
              if [ "${check_status[$msg]}" = "true" ]; then
                  echo "ERROR: $msg" >&2
                  fail=true
              fi
          done
          if ! git diff --exit-code; then
            echo "ERROR: There are changes after trying to generate and formatting" >&2
            fail=true
          fi
          if [ "$fail" = true ]; then
              exit 1
          fi
          echo "All checks passed successfully"

  build-migrate:
    name: Build Migrate
    runs-on: ubuntu-latest
    needs: check
    if: >-
      ${{
        startsWith(github.ref, 'refs/tags/v') ||
        (github.event_name == 'workflow_dispatch' && inputs.release == 'true')
      }}
    concurrency: build-migrate
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: jdx/mise-action@v3
        with:
          experimental: true

      - name: gen migration
        run: just atlas-gen-migration

      - uses: EndBug/add-and-commit@v9
        id: add-and-commit
        with:
          add: migration/
          message: |-
            build(migration): update migration
            [skip ci]

      - name: Login
        if: ${{ steps.add-and-commit.outputs.committed == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.add-and-commit.outputs.committed == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/migrate.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/migrate:latest
            ghcr.io/${{ github.repository_owner }}/migrate:${{ steps.add-and-commit.outputs.commit_long_sha }}
            ghcr.io/${{ github.repository_owner }}/migrate:${{ github.ref_name }}

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs:
      - check
    if: >-
      ${{
        startsWith(github.ref, 'refs/tags/v') ||
        (github.event_name == 'workflow_dispatch' && inputs.release == 'true')
      }}
    concurrency: build-backend
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get commit hash
        id: commit-hash
        working-directory: .
        run: echo "commit=$(git rev-parse HEAD)" >>"${GITHUB_OUTPUT}"

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/backend.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.commit-hash.outputs.commit }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  swagger:
    name: Deploy swagger page
    runs-on: ubuntu-latest
    concurrency: swagger
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: jdx/mise-action@v3
        with:
          experimental: true

      - name: Install go deps
        run: go mod download

      - run: just gen-swag

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  update-kube:
    name: Update Kubernetes Manifest
    runs-on: ubuntu-latest
    needs:
      - build-backend
      - build-migrate
    if: >-
      ${{
        (startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch') &&
        (needs.build-backend.result == 'success') &&
        (needs.build-migrate.result == 'success')
      }}
    steps:
      - name: Get token
        id: get-token
        uses: actions/create-github-app-token@v2
        with:
          private-key: ${{ secrets.ORG_BOT_PRIVATE_KEY }}
          app-id: ${{ vars.ORG_BOT_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: infrastructure

      - name: Trigger Renovate
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.get-token.outputs.token }}
          repository: ${{ github.repository_owner }}/infrastructure
          event-type: renovate
          client-payload: |- # language: json
            {
              "images": "ghcr.io/${{ github.repository }},ghcr.io/${{ github.repository_owner }}/migrate"
            }
